language: node_js
node_js:
  - "11"

cache:
  directories:
    - ./node_modules
    - ./tests/ng-project/node_modules

install:
  - yarn install

script:
  - yarn clean
  - yarn lint
  - yarn check-format
  - yarn build
  - yarn itest-build
